### ISSUE TITLE
Add new binder dynamically

### ISSUE THREAD

**Issue by silviahisham** [yqritc/RecyclerView-MultipleViewTypesAdapter#11]
is it possible to add a new binder dynamically after already initializing `EnumListBindAdapter` and using `addAllBinder` in the constructor?  I have a different row type that i want to add if a certain condition is met, and removed if not.

**Comment by yqritc** [comment]
@silviahisham 
Since recyclerview cache the mapping between view type and view holder, you cannot dynamically replace binders. So, please initialize all binders at first and manage the items by setting item count zero in the binder if a certain condition is met.

**Comment by silviahisham** [comment]
Thanks I tried what you suggested and it worked.
