### ISSUE TITLE
getItemViewType in EnumMapBindAdapter

### ISSUE THREAD

**Issue by silviahisham** [yqritc/RecyclerView-MultipleViewTypesAdapter#12]
What does `getITemViewType` do in `EnumMapBindAdapter` exactly? and what if I have one arraylist of different object types and not separate lists, how can I change view types based on object type?, if I use separate binders then i have to have separate lists, so I tried using one binder and override getItemViewType in it, but turned out I can't since it extends ViewHolder.

**Comment by yqritc** [comment]
The idea of this library is to separates the logic for each view type into single class (DataBinder), and change the role of adapter class (DataBindAdapter) to manage these DataBinder classes. 
So, you need to write logic to separate object depending on view types. 
If you don want to separate the list and manage by single class, then you don need to use this library. just follow standard way to manage class by extending RecyclerView.Adapter.
