### ISSUE TITLE
Cannot be cast to ...

### ISSUE THREAD

**Issue by slott** [yqritc/RecyclerView-MultipleViewTypesAdapter#17]
Every now and then I end up getting a class cast exception such as:

> java.lang.ClassCastException: com.vivino.android.marketsection.binders.ComputationalTopListsBinder$ViewHolder cannot be cast to com.vivino.android.marketsection.binders.HighlightedOfferBinder$ViewHolder

Seems its picking the wrong binder at the wrong time and then things go south...

This happens only when I use my custom adapter with support for removeBinder - So not really your wrong doing..

**Comment by Deepscorn** [comment]
I didn't see a way for algorithm to see that you really removed binder. If you delete binder the way you suggested in https://github.com/yqritc/RecyclerView-MultipleViewTypesAdapter/issues/16#issuecomment-275601464 Then you are just removing an item from mBinderList which is a regular List in ListBindAdapter. 
That way, it is not an issue
