### ISSUE TITLE
unbindViewHolder

### ISSUE THREAD

**Issue by winsonlim** [yqritc/RecyclerView-MultipleViewTypesAdapter#3]
Hi,

May I ask if the DataBinder has any capability of an unbindViewHolder callback?

**Comment by yqritc** [comment]
@winsonlim 
no such method is defined in DataBinder.
but, if any method such as onViewDetachedFromWindow (VH holder) defined in RecyclerView.Adapter matches your needs, you can simply create your custom classes based on mine and override its method.

**Comment by winsonlim** [comment]
Thanks @yqritc! Great idea on onViewAttachedToWindow and onViewDetachedFromWindow

**Comment by yqritc** [comment]
Hope it works well!!
