### ISSUE TITLE
two dynamic lists

### ISSUE THREAD

**Issue by narinearraul** [yqritc/RecyclerView-MultipleViewTypesAdapter#5]
Does this library support two dynamic lists? For example if I have two different binders that each have a dynamic list, would I need to do anything differently to get it to work? 

Currently I'm getting indexing issues when using ListBindAdapter. 
What's the best way to do this? thanks in advance

**Comment by yqritc** [comment]
After adding/removing/replacing items in binder, you need to notify dataset changed methods like the following line.
https://github.com/yqritc/RecyclerView-MultipleViewTypesAdapter/blob/master/sample/src/main/java/com/yqritc/recyclerviewmultipleviewtypesadapter/sample/binder/Sample2Binder.java#L54

**Comment by narinearraul** [comment]
I realized that my issue was I was overriding the getItemViewType method and that was causing issues with my two different lists since they are dynamic. I ended up removing my own version of the getItemViewType and seems to be working perfectly. 

Thanks for the help!!
