### ISSUE TITLE
what if the other linearlayout is gridview which is bind to layout that is not gridview?

### ISSUE THREAD

**Issue by cabuhatprince** [yqritc/RecyclerView-MultipleViewTypesAdapter#7]

**Comment by yqritc** [comment]
@cabuhatprince 
Sorry, I don't get what you mean.
This is the library for recyclerview.
Please explain more in detail.

**Comment by cabuhatprince** [comment]
![screen shot 2015-08-28 at 7 57 17 pm](https://cloud.githubusercontent.com/assets/8501329/9545747/2393d28c-4dbf-11e5-95ed-daee979c9ab5.png)

hi, im trying to display this two in one view then i use your framework, but i dont know how to display the gridviewlayout in which i also have a linearlayout view please see the picture thankyouuuuu.

**Comment by yqritc** [comment]
@cabuhatprince 

Sorry, it's still not so clear for me what u are asking me><

Are u trying to make the above layout by using recyclerview?
If yes, u need to define view types for the layout.
eg. 
- ViewType1: "Fun Run..." layout
- ViewType2: The layout consisting of icon and text
- ViewType3: bold text label
- ViewType4: gridViewLayout (if it's layout is scrollable, u may be able to use horizontal recyclerview)
- ViewType5: paw print layout including icon, name?, date, comment?
- ViewType6: edittext and button

Maybe the above classification is too complex... 
Please consider how do u classify in terms of view reusability. (the layout may be better to create by not using recyclerview, but scrollview + LinearLayout)
Then, create data binder classes for each view type and manage binders by creating DataBindAdapter class.

Hope this helps you...
