### ISSUE TITLE
how to implements StaggeredGridLayoutManager with the multipleViewTypesAdapter

### ISSUE THREAD

**Issue by leonzhuhi** [yqritc/RecyclerView-MultipleViewTypesAdapter#8]
thank you for your great multipleViewTypesAdapter.

but when i used it wanting to show a  StaggeredGrid UI, i found something undesirably.

it can not show staggerGrid but the different children has the same height . 

So how to implement StaggeredGrid with multipleViewTypesAdapter,thanks a lot.

as my code:
MainActivity.java

onCreate(Bundle savedInstanceState) {
...
RecyclerView recyclerView = (RecyclerView) findViewById(R.id.recyclerview_main);
        SampleEnumListAdapter adapter = new SampleEnumListAdapter();
        recyclerView.setAdapter(adapter);
//       recyclerView.setLayoutManager(new LinearLayoutManager(this));
        // 瀑布流
        recyclerView.setLayoutManager(new StaggeredGridLayoutManager(2,
                StaggeredGridLayoutManager.VERTICAL));
        // 自定义分割线
//      SpacesItemDecoration decoration = new SpacesItemDecoration(this,
//              SpacesItemDecoration.VERTICAL_LIST);
//      recyclerView.addItemDecoration(decoration);
        // -----------//
        List<SampleData> sampleData = getSampleData();
        adapter.setSample2Data(sampleData);
...

}

and the different binder 

Sample1Binder.java

@Override
    public void bindViewHolder(ViewHolder holder, int position) {
        ViewGroup.LayoutParams params = holder.itemView.getLayoutParams();// 得到item的LayoutParams布局参数
        params.height = 50;// 把随机的高度赋予item布局
        holder.itemView.setLayoutParams(params);// 把params设置给item布局

```
    Picasso.with(holder.mImageView.getContext())
    .load(R.drawable.bird)
    .into(holder.mImageView);
}
```

Simple2Binder.java

 @Override
    public void bindViewHolder(ViewHolder holder, int position) {
        ViewGroup.LayoutParams params = holder.itemView.getLayoutParams();// 得到item的LayoutParams布局参数
        params.height = 100;// 把随机的高度赋予item布局
        holder.itemView.setLayoutParams(params);// 把params设置给item布局

```
    SampleData data = mDataSet.get(position);
    holder.mTitleText.setText(data.mTitle);
    holder.mContent.setText(data.mContent);
    holder.mImageView.setImageResource(R.drawable.animal1);

}
```

Sample3Binder.java

 public void bindViewHolder(ViewHolder holder, int position) {
    ViewGroup.LayoutParams params = holder.itemView.getLayoutParams();// 得到item的LayoutParams布局参数
        params.height = 150;// 把随机的高度赋予item布局
        holder.itemView.setLayoutParams(params);// 把params设置给item布局

```
    holder.mImageView.setImageResource(R.drawable.animal3);

}
```

**Comment by yqritc** [comment]
@leonzhuhi 
This is not about this library, but you should be able to change the item height depending on view types.
Based on my sample project, simply set the following in activity.

```
recyclerView.setLayoutManager(new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL));
```

then, set different height for items in binders

```
@Override
public void bindViewHolder(ViewHolder holder, int position) {
   holder.itemView.getLayoutParams().height = 1000; // change the size as u needed
   .
   .
   .
}
```

You will see different height for each items depending on view type.
